### ISSUE TITLE
Support dynamic value related to date and time in text

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#5]
## Background
Allows you to quickly insert date and time information. 

## Example

```
Snippet {
  keyword: "dtnow",
  text: "%yyyy%-%MM%-%dd% %HH%:%mm%:%ss"
}
```

When expanded, the text will become `2020-05-25 10:36:08`.

## To-dos
- [x] Highlight placeholder with gray background color
- [x] Change placeholder's typeface to monospace
- [x] When expanding text, replace placeholder with its designated value
- [x] Show list of date/time placeholders when adding/editing a snippet
- [x] Tap on a date/time placeholder will insert the placeholder to where the cursor is in the text field
- [x] 12 hour clock format support

~- [ ] Remove inserted placeholder when tapped~
~- [ ] Polish the placeholder in all screen (Add, Edit, List)~

## Thoughts
In the first iteration, it will only support current time. Supported values are as follow.

Year:
- 2 digit number, e.g. 20 (`%yy%`)
- 4 digit number, e.g. 2020 (`%yyyy%`)

Month:
- 1 digit number, e.g. 5 (`%M%`)
- 2 digit number, e.g. 05 (`%MM%`)
- Short text, e.g. Jun (`%MMM%`)
- Full text, e.g. June (`%MMMM%`)

Day:
- Day of month, 1 digit number, e.g. 1 (`%d%`)
- Day of month, 2 digit number, e.g. 01 (`%dd%`)
- Day of week, short text, e.g. Sun (`%EE%`)
- Day of week, full text, e.g. Sunday (`%EEEE%`)

Hour:
- 1 digit number, e.g. 9 (`%H%`)
- 2 digit number, e.g. 09 (`%HH%`)

Minute:
- 1 digit number, e.g. 8 (`%m%`)
- 2 digit number, e.g. 08 (`%mm%`)

Second:
- 1 digit number, e.g. 2 (`%s%`)
- 2 digit number, e.g. 02 (`%ss%`)

Week:
- Week of year, number, e.g. 21 (`%w%`)

With these placeholders in place, everyone can create any date/time information in format they wish. Hence, there won't be a "special snippet" such as `%current_date%` or `%current_time%`, which people will eventually would like to configure the format.

**Comment by illumi241** [comment]
Please also support formating for those date and time strings, like for example dd.mm.yy.

**Comment by sensen** [comment]
I've updated the description to clearly describe what I have in mind for this feature. @illumi241

**Comment by sensen** [comment]
The following will be supported.

Year:
- 2 digit number, e.g. 20 (`%yy%`)
- 4 digit number, e.g. 2020 (`%yyyy%`)

Month:
- 1 digit number, e.g. 5 (`%M%`)
- 2 digit number, e.g. 05 (`%MM%`)
- Short text, e.g. Jun (`%MMM%`)
- Full text, e.g. June (`%MMMM%`)

Day:
- Day of month, 1 digit number, e.g. 1 (`%d%`)
- Day of month, 2 digit number, e.g. 01 (`%dd%`)
- Day of week, short text, e.g. Sun (`%EE%`)
- Day of week, full text, e.g. Sunday (`%EEEE%`)

Hour:
- 1 digit number, e.g. 9 (`%H%`)
- 2 digit number, e.g. 09 (`%HH%`)

Minute:
- 1 digit number, e.g. 8 (`%m%`)
- 2 digit number, e.g. 08 (`%mm%`)

Second:
- 1 digit number, e.g. 2 (`%s%`)
- 2 digit number, e.g. 02 (`%ss%`)

Week:
- Week of year, number, e.g. 21 (`%w%`)

If a placeholder (`%xxxx%`) is found in the `text` of a snippet, it will be replaced with its designated value.

**Comment by sensen** [comment]
Published.
